### ISSUE TITLE
Link texts in Markdown files should be translated

### ISSUE THREAD

**Issue by NextTurn** [dotnet/docs.es-es#122] opened 2019-04-03 16:08 UTC

**Comment by CeciAc** [comment] 2019-04-03 16:46
Hello, @NextTurn 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by NextTurn** [comment] 2019-04-04 02:44
For example

dotnet/docs.ko-kr#92
dotnet/docs.cs-cz#12
dotnet/docs.es-es#106
dotnet/docs.de-de#127
dotnet/docs.pl-pl#191
dotnet/docs.it-it#59

**Comment by CeciAc** [comment] 2019-04-04 13:13
Hello @NextTurn 
I see those issues are being worked in the mentioned channels,

It's not clear what you are requesting in this issue

Kind regards,
Microsoft DOCS International Team

**Comment by NextTurn** [comment] 2019-04-04 14:45
These are examples of untranslated contents. There are a lot of other occurrences. Do you want me to fix all of them?

**Comment by DavidPrio** [comment] 2019-04-04 19:32
Hi @JasonCard can you please investigate this?
CC @SunnyDeng @CeciAc

**Comment by JasonCard** [comment] 2019-04-05 03:37
Hi @NextTurn 
Thank you for raising this issue.
We will look into this and update.

**Comment by JasonCard** [comment] 2019-04-26 19:26
Hi @NextTurn, 

I'm sorry for the delay.
We've figured out the root cause of this issue and are working to addressing it.
Translators had instructions to leave link texts in English if linked article was not translated at that time. 
However, we do not review and change previously translated strings unless that particular sentence with link text is updated. So even after linked article was translated, the link text remained in English.
We are changing this instruction to always translate link texts even if linked article is in English to prevent this issue going forward.
For existing link texts left in English, it is difficult to globally search and fix all occurences, as some terms are left in English by-design. We are working on a tool and process to efficiently clean them up. This will take some time, so we would like to ask for your patience on this matter.
For now, we reviewed [this particular article](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference) that you opened PRs for in all languages and fixed link texts left in English. So I would like to close this issue for now, but we will be following up on addressing the rest of articles and content.
Thank you for your feedback as always and please let me know if you have any questions or concerns.

Kind regards,
Microsoft DOCS International Team

**Closed by JasonCard** 2019-04-26 19:26 UTC
Labels: Needs-more-info
